#!/usr/bin/env bash
iDIR="$HOME/.config/waybar/icons"
# Get brightness
get_backlight() {
	LIGHT=$(printf "%.0f\n" $(brightnessctl i))
	echo "${LIGHT}%"
}
# Get icons
get_icon() {
	backlight="$(brightnessctl g)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "500") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "500") && ("$current" -le "10000") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "10000") && ("$current" -le "15000") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "15000") && ("$current" -le "20000") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "20000") && ("$current" -le "24000") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
	echo $icon
}
get_pct() {
	backlight="$(brightnessctl g)"
	echo "$((($backlight * 100) / 24000))"
}
# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Brightness : $(get_pct) %"
}
# Increase brightness
inc_backlight() {
	brightnessctl set 10%+ && get_icon && notify_user
}
# Decrease brightness
dec_backlight() {
	current_pct=$(get_pct)
	if [[ $current_pct -le 10 ]]; then
		notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Brightness at minimum (${current_pct}%)"
		return
	fi
	brightnessctl set 10%- && get_icon && notify_user
}
# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
